server_connect_timeout: 5000
custom_server_name: Bolt
forge_support: false
always_handle_packets: false
player_limit: -1
ip_forward: true
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.ip
  - bungeecord.command.reload
  - nerve.staff
timeout: 30000
log_commands: false
online_mode: true
listeners:
- query_port: 25565
  motd: '&6&lBOLT &e&l⚡ &r&7| &eClosed Beta\n&7Join today @ bolt.rip'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 999
  tab_size: 60
  force_default_server: false
log_pings: false
remote_ping_timeout: 5000
disabled_commands:
- disabledcommandhere
network_compression_threshold: 256
remote_ping_cache: -1
connection_throttle: 4000
stats: 85e8fa6c-c86a-4763-bd31-9425cf247115
connection_throttle_limit: 3
groups:
  Indicado:
  - admin
  unixfox:
  - admin
  dentmaged:
  - admin
  Picajoluna:
  - admin
prevent_proxy_connections: false
