name: Docker

on:
  push:
  repository_dispatch:
    types:
      - build

jobs:
  build-bungee:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup SSH Keys and known_hosts
        run: |
            echo "${{ secrets.SSH_KEY }}" > id_rsa

      - name: Docker Build
        uses: benjlevesque/actions-docker-gcr/build@v1.1
        with:
          image: ${{ secrets.GOOGLE_PROJECT_ID }}/bolt-bungee
          tag: master

      - name: Docker Push
        uses: benjlevesque/actions-docker-gcr/push@v1.1
        with:
          gcloud_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          image: ${{ secrets.GOOGLE_PROJECT_ID }}/bolt-bungee
          tag: master
  
  build-typhoon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Docker Build
        uses: unixfox/actions-docker-gcr/build@master
        with:
          image: ${{ secrets.GOOGLE_PROJECT_ID }}/bolt-fallbacklobby
          tag: master
          dockerfile: Dockerfile.TyphoonLimbo

      - name: Docker Push
        uses: benjlevesque/actions-docker-gcr/push@v1.1
        with:
          gcloud_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          image: ${{ secrets.GOOGLE_PROJECT_ID }}/bolt-fallbacklobby
          tag: master